import base64

from app.config import settings
from brevo import Brevo
from brevo.transactional_emails import (
    SendTransacEmailRequestAttachmentItem,
    SendTransacEmailRequestSender,
    SendTransacEmailRequestToItem,
)


def send_analysis_report(
    to_email: str,
    portfolio_name: str,
    report: str,
    actions: list[dict],
    csv_bytes: bytes | None = None,
    csv_filename: str | None = None,
) -> str | None:
    """Send the full CAT analysis report as an HTML email, with optional CSV attachment."""
    if not settings.brevo_api_key:
        raise RuntimeError("BREVO_API_KEY is not configured")
    if not settings.brevo_sender_email:
        raise RuntimeError("BREVO_SENDER_EMAIL is not configured")

    actions_html = "".join(
        f"<tr><td style='padding:6px 12px;font-weight:bold;color:#c0392b'>{a.get('priority','')}</td>"
        f"<td style='padding:6px 12px;font-weight:bold'>{a.get('action','')}</td>"
        f"<td style='padding:6px 12px;color:#555'>{a.get('rationale','')}</td></tr>"
        for a in actions
    )
    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:800px;margin:auto;color:#222">
      <h2 style="color:#1a5276">Flood Risk Analysis Report</h2>
      <h3 style="color:#555">{portfolio_name}</h3>
      <hr/>
      <div style="white-space:pre-wrap;line-height:1.7">{report}</div>
      <h3 style="color:#1a5276;margin-top:32px">Recommended Actions</h3>
      <table style="border-collapse:collapse;width:100%">
        <thead><tr style="background:#1a5276;color:#fff">
          <th style="padding:8px 12px;text-align:left">Priority</th>
          <th style="padding:8px 12px;text-align:left">Action</th>
          <th style="padding:8px 12px;text-align:left">Rationale</th>
        </tr></thead>
        <tbody>{actions_html}</tbody>
      </table>
      <p style="color:#aaa;font-size:12px;margin-top:40px">Generated by Fusion CAT Platform</p>
    </body></html>
    """

    attachments = []
    if csv_bytes and csv_filename:
        attachments.append(SendTransacEmailRequestAttachmentItem(
            name=csv_filename,
            content=base64.b64encode(csv_bytes).decode("ascii"),
        ))

    client = Brevo(api_key=settings.brevo_api_key, timeout=30.0)
    response = client.transactional_emails.send_transac_email(
        sender=SendTransacEmailRequestSender(
            email=settings.brevo_sender_email,
            name=settings.brevo_sender_name,
        ),
        to=[SendTransacEmailRequestToItem(email=to_email)],
        subject=f"Flood Risk Analysis Report: {portfolio_name}",
        html_content=html,
        attachment=attachments or None,
    )
    return response.message_id


def send_portfolio_csv(to_email: str, portfolio_name: str, filename: str, csv_bytes: bytes) -> str | None:
    if not settings.brevo_api_key:
        raise RuntimeError("BREVO_API_KEY is not configured")
    if not settings.brevo_sender_email:
        raise RuntimeError("BREVO_SENDER_EMAIL is not configured")

    client = Brevo(api_key=settings.brevo_api_key, timeout=30.0)
    response = client.transactional_emails.send_transac_email(
        sender=SendTransacEmailRequestSender(
            email=settings.brevo_sender_email,
            name=settings.brevo_sender_name,
        ),
        to=[SendTransacEmailRequestToItem(email=to_email)],
        subject=f"Your approved portfolio: {portfolio_name}",
        text_content=f"Attached is the approved exposure and hazard data for {portfolio_name}.",
        attachment=[SendTransacEmailRequestAttachmentItem(
            name=filename,
            content=base64.b64encode(csv_bytes).decode("ascii"),
        )],
    )
    return response.message_id
